// Write a Markdown index of the Deadworks API (hooks, events, enums, types) from
// lib/DeadworksManaged.Api.dll (reflection) and its .xml doc comments.
// Usage: dotnet run scripts/api-index.cs [lib dir] [output .md]. See api-index.cs.md.
#:property PublishAot=false
using System.Reflection;
using System.Text;
using System.Xml.Linq;

var root = Path.GetFullPath(Path.Combine(AppContext.GetData("EntryPointFileDirectoryPath") as string ?? ".", ".."));
var libDir = Path.GetFullPath(args.Length > 0 ? args[0] : Path.Combine(root, "lib"));
var output = Path.GetFullPath(args.Length > 1 ? args[1] : Path.Combine(root, "knowledge", "generated", "deadworks-api.md"));

AppDomain.CurrentDomain.AssemblyResolve += (_, e) =>
{
  var candidate = Path.Combine(libDir, new AssemblyName(e.Name).Name + ".dll");
  return File.Exists(candidate) ? Assembly.LoadFrom(candidate) : null;
};
var api = Assembly.LoadFrom(Path.Combine(libDir, "DeadworksManaged.Api.dll"));
var version = File.Exists(Path.Combine(libDir, ".version")) ? File.ReadAllText(Path.Combine(libDir, ".version")).Trim() : "unknown";

// Doc summaries keyed by "Namespace.Type" and "Namespace.Type.Member" (overloads share the first).
var docs = new Dictionary<string, string>();
var xmlPath = Path.Combine(libDir, "DeadworksManaged.Api.xml");
if (File.Exists(xmlPath))
{
  foreach (var member in XDocument.Load(xmlPath).Descendants("member"))
  {
    var name = member.Attribute("name")?.Value;
    var summary = member.Element("summary");
    if (name is null || summary is null) continue;
    var key = name[2..].Split('(')[0].Replace("#ctor", "ctor");
    var text = string.Join(" ", string.Concat(summary.Nodes().Select(NodeText)).Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
    docs.TryAdd(key, text);
  }
}

static string NodeText(XNode node) => node switch
{
  XText t => t.Value,
  XElement e when e.Attribute("cref") is { } cref => "`" + cref.Value[2..].Split('(')[0].Split('.').Last() + "`",
  XElement e when e.Attribute("name") is { } n => "`" + n.Value + "`",
  XElement e => string.Concat(e.Nodes().Select(NodeText)),
  _ => "",
};

Type[] types;
try { types = api.GetExportedTypes(); }
catch (ReflectionTypeLoadException ex) { types = ex.Types.Where(t => t is not null).ToArray()!; }

bool IsApi(Type t) => t.Namespace?.StartsWith("DeadworksManaged.Api") == true && !t.Name.Contains('<');
string Doc(string key) => docs.TryGetValue(key, out var d) ? d.Replace("|", "\\|") : "";
string TypeKey(Type t) => (t.FullName ?? t.Name).Replace('+', '.').Split('`')[0] + (t.IsGenericType ? "`" + t.GetGenericArguments().Length : "");
string Short(Type t)
{
  if (t.IsGenericType)
    return t.Name.Split('`')[0] + "<" + string.Join(", ", t.GetGenericArguments().Select(Short)) + ">";
  if (t.IsArray) return Short(t.GetElementType()!) + "[]";
  return Nullable.GetUnderlyingType(t) is { } u ? Short(u) + "?" : t.Name switch
  {
    "Void" => "void", "Boolean" => "bool", "Int32" => "int", "Int64" => "long", "UInt64" => "ulong",
    "Single" => "float", "Double" => "double", "String" => "string", "Object" => "object", "Byte" => "byte",
    "UInt32" => "uint", "Int16" => "short", "UInt16" => "ushort",
    _ => t.Name,
  };
}
string Params(MethodBase m) => string.Join(", ", m.GetParameters().Select(p => $"{Short(p.ParameterType)} {p.Name}"));

var apiTypes = types.Where(IsApi).OrderBy(t => t.FullName).ToList();
var md = new StringBuilder();
md.AppendLine("---");
md.AppendLine("type: generated-reference");
md.AppendLine($"source: DeadworksManaged.Api {version}");
md.AppendLine($"generated: {DateTime.UtcNow:yyyy-MM-dd}");
md.AppendLine("generator: scripts/api-index.cs");
md.AppendLine("---");
md.AppendLine();
md.AppendLine($"# Deadworks API index ({version})");
md.AppendLine();
md.AppendLine("Generated by `scripts/api-index.cs`; do not edit by hand. Everything a plugin can");
md.AppendLine("touch in the game, from reflection plus the API's doc comments. Grep it rather");
md.AppendLine("than reading it top to bottom. Names here are real; behavior in game is only");
md.AppendLine("verified where `knowledge/effects-catalog.md` or `reference/resources.md` says so.");
md.AppendLine();

// 1. Plugin hooks
var plugin = apiTypes.FirstOrDefault(t => t.Name == "IDeadworksPlugin");
if (plugin is not null)
{
  md.AppendLine("## Plugin hooks (`IDeadworksPlugin`)");
  md.AppendLine();
  md.AppendLine("| Hook | Summary |");
  md.AppendLine("|---|---|");
  foreach (var m in plugin.GetMethods().Where(m => !m.IsSpecialName).OrderBy(m => m.Name))
    md.AppendLine($"| `{Short(m.ReturnType)} {m.Name}({Params(m)})` | {Doc($"{TypeKey(plugin)}.{m.Name}")} |");
  md.AppendLine();
}

// 2. Game events ([GameEventHandler("name")] payload classes)
var events = apiTypes.Where(t => t.IsClass && !t.IsAbstract && t.Name.EndsWith("Event") && t.BaseType?.Name == "GameEvent").ToList();
if (events.Count > 0)
{
  md.AppendLine($"## Game events ({events.Count})");
  md.AppendLine();
  md.AppendLine("Payload classes for `[GameEventHandler(\"event_name\")]` (e.g. `player_death` → `PlayerDeathEvent`). Fields listed per event.");
  md.AppendLine();
  foreach (var t in events)
  {
    var props = t.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).Select(p => p.Name);
    md.AppendLine($"- **{t.Name}**: {string.Join(", ", props)}");
  }
  md.AppendLine();
}

// 3. Enums
var enums = apiTypes.Where(t => t.IsEnum).ToList();
md.AppendLine($"## Enums ({enums.Count})");
md.AppendLine();
foreach (var t in enums)
{
  var names = Enum.GetNames(t);
  var underlying = Enum.GetUnderlyingType(t);
  var values = names.Select(n => $"{n}={Convert.ChangeType(Enum.Parse(t, n), underlying)}");
  var summary = Doc(TypeKey(t));
  md.AppendLine($"### {t.Name} ({names.Length})");
  md.AppendLine();
  if (summary.Length > 0) { md.AppendLine(summary); md.AppendLine(); }
  md.AppendLine(string.Join(", ", values));
  md.AppendLine();
}

// 4. Types and members
md.AppendLine("## Types");
md.AppendLine();
foreach (var t in apiTypes.Where(t => !t.IsEnum && !events.Contains(t)))
{
  var key = TypeKey(t);
  md.AppendLine($"### {key.Replace("DeadworksManaged.Api.", "")}");
  md.AppendLine();
  var summary = Doc(key);
  if (summary.Length > 0) { md.AppendLine(summary); md.AppendLine(); }
  const BindingFlags flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;
  var lines = new List<string>();
  foreach (var p in t.GetProperties(flags).OrderBy(p => p.Name))
    lines.Add($"- `{Short(p.PropertyType)} {p.Name}`{(p.GetMethod?.IsStatic == true ? " (static)" : "")}{Suffix(Doc($"{key}.{p.Name}"))}");
  foreach (var f in t.GetFields(flags).Where(f => !f.IsSpecialName).OrderBy(f => f.Name))
    lines.Add($"- `{Short(f.FieldType)} {f.Name}`{(f.IsStatic ? " (static)" : "")}{Suffix(Doc($"{key}.{f.Name}"))}");
  foreach (var m in t.GetMethods(flags).Where(m => !m.IsSpecialName).OrderBy(m => m.Name))
    lines.Add($"- `{Short(m.ReturnType)} {m.Name}({Params(m)})`{(m.IsStatic ? " (static)" : "")}{Suffix(Doc($"{key}.{m.Name}"))}");
  md.AppendLine(lines.Count > 0 ? string.Join("\n", lines.Distinct()) : "_(no public members)_");
  md.AppendLine();
}

// 5. Net messages (protobuf types outside the Api namespace), names only
var messages = types.Where(t => !IsApi(t) && t.GetInterfaces().Any(i => i.Name.StartsWith("IMessage")) && t.DeclaringType is null)
  .Select(t => t.Name).Distinct().OrderBy(n => n).ToList();
md.AppendLine($"## Net messages ({messages.Count})");
md.AppendLine();
md.AppendLine("Protobuf message types usable with `NetMessages.Send` / `[NetMessageHandler]`. `CCitadelUserMsg_*` are the Deadlock-specific UI and effect messages.");
md.AppendLine();
md.AppendLine(string.Join(", ", messages.Select(n => $"`{n}`")));

Directory.CreateDirectory(Path.GetDirectoryName(output)!);
File.WriteAllText(output, md.ToString());
Console.WriteLine($"Wrote {output} ({apiTypes.Count} types, {enums.Count} enums, {events.Count} events, {messages.Count} messages).");

static string Suffix(string doc) => doc.Length > 0 ? ": " + doc : "";
